### ISSUE TITLE
Not a real issue!

### ISSUE THREAD

**Issue by aaronransley** [garfieldnate/garfieldnate.github.io#6]
Hiya @garfieldnate, just wanted to drop a note saying thank you for the source, and for the wonderful `./GOTCHA.md` file. One rarely sees such a tidy list of footguns in one spot, and it's made my experimentation with Astro much more enjoyable.

All the best, feel free to close out 👍

**Comment by garfieldnate** [comment]
Thank you for the kind words, and I'm glad it was so helpful to you :D. Properly the footguns should be tickets in Astro or other projects, but I'll need to update before opening any.
